[package]
authors = ["guillem.cordoba@gmail.com"]
edition = "2018"
name = "file_storage"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "file_storage"

[dependencies]
derive_more = "0"
serde = "1"

holochain_file_storage_zome = {git = "https://github.com/holochain-open-dev/file-storage", branch = "main", package = "holochain_file_storage_zome"}
